# Generated by Django 6.0.8 on 2026-08-07 19:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Designates whether this record has been soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('display_name', models.CharField(blank=True, help_text="Customer's preferred or known name", max_length=255, verbose_name='display name')),
                ('primary_phone', models.CharField(blank=True, db_index=True, help_text='Normalized primary contact phone number if known', max_length=50, verbose_name='primary phone')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Contact email address if known', max_length=254, verbose_name='email address')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about client preferences, history, or special requests', verbose_name='internal notes')),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the customer first interacted with the studio', verbose_name='first seen at')),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp of the most recent interaction', verbose_name='last seen at')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['-last_seen_at'], name='customers_c_last_se_4c6b3a_idx'), models.Index(fields=['display_name'], name='customers_c_display_4c9536_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('channel', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp')], db_index=True, help_text='Communication channel platform', max_length=20, verbose_name='channel')),
                ('external_user_id', models.CharField(db_index=True, help_text='Stable Meta ID: Instagram Scoped ID (IGSID) or WhatsApp ID (WAID)', max_length=255, verbose_name='external user id')),
                ('username', models.CharField(blank=True, help_text='External handle / display username if available (mutable)', max_length=255, verbose_name='username')),
                ('normalized_phone', models.CharField(blank=True, db_index=True, help_text='E.164 normalized phone number where available', max_length=50, verbose_name='normalized phone')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Platform-specific profile details or webhook payload context', verbose_name='metadata')),
                ('customer', models.ForeignKey(help_text='The customer record this external identity maps to', on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='customers.customer')),
            ],
            options={
                'verbose_name': 'customer identity',
                'verbose_name_plural': 'customer identities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'external_user_id'], name='customers_c_channel_82a7e1_idx'), models.Index(fields=['channel', 'username'], name='customers_c_channel_a3c768_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel', 'external_user_id'), name='unique_channel_external_user_id')],
            },
        ),
    ]
