# Generated by Django 5.2.15 on 2026-08-16 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(help_text='The organization this customer belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organizations.organization'),
        ),
    ]
