# Generated by Django 6.0.8 on 2026-09-05 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_organization'),
        ('organizations', '0004_organization_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customeridentity',
            name='unique_channel_external_user_id',
        ),
        migrations.AddField(
            model_name='customeridentity',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='customeridentity',
            constraint=models.UniqueConstraint(fields=('organization', 'channel', 'external_user_id'), name='unique_tenant_channel_identity'),
        ),
    ]
