# Generated by Django 5.2.15 on 2026-08-22 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_email', models.EmailField(max_length=255, verbose_name='admin email')),
                ('action', models.CharField(max_length=100, verbose_name='action name')),
                ('target_type', models.CharField(blank=True, max_length=100, verbose_name='target entity type')),
                ('target_id', models.CharField(blank=True, max_length=255, verbose_name='target entity ID')),
                ('target_name', models.CharField(blank=True, max_length=255, verbose_name='target name')),
                ('previous_state', models.JSONField(blank=True, default=dict, verbose_name='previous state')),
                ('new_state', models.JSONField(blank=True, default=dict, verbose_name='new state')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin audit log',
                'verbose_name_plural': 'admin audit logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
