# Generated by Django 6.0.8 on 2026-08-07 19:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographyService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Designates whether this record has been soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('name', models.CharField(help_text='e.g. Newborn Baby Shoot, Maternity Photoshoot', max_length=255, unique=True, verbose_name='service name')),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Detailed overview of the photography service', verbose_name='description')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Standard base price in studio currency', max_digits=10, verbose_name='base price')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Expected duration of the session in minutes', verbose_name='duration in minutes')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this service is currently available for booking', verbose_name='is active')),
            ],
            options={
                'verbose_name': 'photography service',
                'verbose_name_plural': 'photography services',
                'ordering': ['name'],
            },
        ),
    ]
