# Generated by Django 6.0.8 on 2026-08-07 19:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Designates whether this record has been soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('name', models.CharField(help_text='e.g. Standard Package, Premium Gold Package', max_length=255, verbose_name='package name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for the package', max_length=255, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Package overview and deliverables summary', verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Fixed price for this package', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='package price')),
                ('duration_minutes_override', models.PositiveIntegerField(blank=True, help_text='Optional duration override if this package differs from base service duration', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='duration override (minutes)')),
                ('inclusions', models.JSONField(blank=True, default=list, help_text="List of deliverables/features included (e.g. ['20 Edited Photos', '2 Outfits'])", verbose_name='package inclusions')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this package is available for customer booking', verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order within the parent service', verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['sort_order', 'price', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='photographyservice',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'photography service', 'verbose_name_plural': 'photography services'},
        ),
        migrations.AddField(
            model_name='photographyservice',
            name='buffer_after_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Tear-down / cleanup / reset buffer after session ends', validators=[django.core.validators.MinValueValidator(0)], verbose_name='buffer after (minutes)'),
        ),
        migrations.AddField(
            model_name='photographyservice',
            name='buffer_before_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Preparation / setup buffer before session begins', validators=[django.core.validators.MinValueValidator(0)], verbose_name='buffer before (minutes)'),
        ),
        migrations.AddField(
            model_name='photographyservice',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order for public booking and admin catalog', verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='photographyservice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting base price in studio currency', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='base price'),
        ),
        migrations.AlterField(
            model_name='photographyservice',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed overview of what the photography session entails', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='photographyservice',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Standard duration of the photography session in minutes', validators=[django.core.validators.MinValueValidator(1)], verbose_name='session duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='photographyservice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this service is currently offered to customers', verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='photographyservice',
            name='slug',
            field=models.SlugField(help_text='URL-friendly slug for service identification', max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AddIndex(
            model_name='photographyservice',
            index=models.Index(fields=['is_active', 'sort_order'], name='services_ph_is_acti_432dcf_idx'),
        ),
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ForeignKey(help_text='The parent photography service offering', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.photographyservice'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['service', 'is_active', 'sort_order'], name='services_pa_service_6eb062_idx'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('service', 'name'), name='unique_service_package_name'),
        ),
    ]
