# Generated by Django 5.2.15 on 2026-08-16 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('services', '0002_package_alter_photographyservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographyservice',
            name='organization',
            field=models.ForeignKey(help_text='The organization this service belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='photographyservice',
            name='name',
            field=models.CharField(help_text='e.g. Newborn Baby Shoot, Maternity Photoshoot', max_length=255, verbose_name='service name'),
        ),
        migrations.AlterField(
            model_name='photographyservice',
            name='slug',
            field=models.SlugField(help_text='URL-friendly slug for service identification', max_length=255, verbose_name='slug'),
        ),
        migrations.AddConstraint(
            model_name='photographyservice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'name'), name='unique_org_service_name'),
        ),
        migrations.AddConstraint(
            model_name='photographyservice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'slug'), name='unique_org_service_slug'),
        ),
    ]
