# Generated by Django 6.0.8 on 2026-08-07 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('channel', models.CharField(choices=[('INSTAGRAM', 'Instagram Direct'), ('WHATSAPP', 'WhatsApp Cloud API')], db_index=True, max_length=20, verbose_name='channel')),
                ('event_id', models.CharField(db_index=True, help_text='Unique identifier or hash of the webhook event for deduplication.', max_length=255, verbose_name='event identifier')),
                ('signature', models.CharField(blank=True, help_text='HMAC signature header sent by Meta.', max_length=255, verbose_name='signature')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='request headers')),
                ('payload', models.JSONField(help_text='Exact JSON body delivered by Meta webhook.', verbose_name='raw payload')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Async Processing'), ('PROCESSING', 'Currently Processing'), ('PROCESSED', 'Successfully Processed'), ('DUPLICATE', 'Duplicate Event Ignored'), ('FAILED', 'Processing Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='processing status')),
                ('messages_count', models.PositiveIntegerField(default=0, help_text='Number of customer messages extracted from this event.', verbose_name='messages count')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
            ],
            options={
                'verbose_name': 'raw webhook event',
                'verbose_name_plural': 'raw webhook events',
                'db_table': 'raw_webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'status', 'created_at'], name='raw_webhook_channel_b6c1db_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel', 'event_id'), name='unique_channel_webhook_event')],
            },
        ),
    ]
