# Generated by Django 5.2.15 on 2026-08-16 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('provider', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp')], db_index=True, max_length=20, verbose_name='provider')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('credentials', models.JSONField(default=dict, help_text='Encrypted or plain credentials (access tokens, phone IDs, etc)', verbose_name='credentials')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Public metadata (e.g. connected page name)', verbose_name='metadata')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_configs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'integration config',
                'verbose_name_plural': 'integration configs',
                'unique_together': {('organization', 'provider')},
            },
        ),
    ]
