# Generated by Django 6.0.8 on 2026-09-05 09:20

import django.db.models.deletion
import django.db.models.fields.json
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_datadeletionrequest'),
        ('organizations', '0005_default_india_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('state_hash', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(max_length=20)),
                ('redirect_uri', models.URLField(blank=True, max_length=1000)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='connected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='integrationconfig',
            constraint=models.UniqueConstraint(models.F('provider'), django.db.models.fields.json.KeyTextTransform('destination_id', 'metadata'), condition=models.Q(('is_active', True), ('metadata__has_key', 'destination_id'), models.Q(('metadata__destination_id', ''), _negated=True)), name='unique_active_meta_destination'),
        ),
        migrations.AddField(
            model_name='oauthattempt',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='oauthattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
