# Generated by Django 6.0.8 on 2026-09-05 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0006_remove_message_unique_external_message_id_and_more'),
        ('leads', '0008_leadform'),
        ('organizations', '0004_organization_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(max_length=160)),
                ('channel', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('trigger_type', models.CharField(choices=[('INCOMING', 'Incoming message'), ('EXACT', 'Exact keyword'), ('CONTAINS', 'Contains keyword'), ('FIRST_INTERACTION', 'First interaction')], max_length=24)),
                ('trigger_value', models.CharField(blank=True, max_length=255)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='organizations.organization')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('action_type', models.CharField(choices=[('SEND_REPLY', 'Send reply'), ('CREATE_LEAD', 'Create lead'), ('CHANGE_STATUS', 'Change status'), ('ADD_TAG', 'Add tag'), ('ASSIGN', 'Assign lead'), ('BOOKING_LINK', 'Send booking link')], max_length=24)),
                ('action_order', models.PositiveSmallIntegerField(default=0)),
                ('configuration', models.JSONField(default=dict)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automations.automation')),
            ],
            options={
                'ordering': ['action_order'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('automation_name', models.CharField(max_length=160)),
                ('status', models.CharField(default='RUNNING', max_length=24)),
                ('result', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('automation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='automations.automation')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.conversation')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('trigger_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_executions', to='conversations.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['organization', 'channel', 'enabled'], name='automations_organiz_79312f_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationaction',
            constraint=models.UniqueConstraint(fields=('automation', 'action_order'), name='unique_automation_action_order'),
        ),
        migrations.AddConstraint(
            model_name='automationexecution',
            constraint=models.UniqueConstraint(fields=('automation', 'trigger_message'), name='unique_automation_trigger_execution'),
        ),
    ]
