# Generated by Django 6.0.8 on 2026-09-05 08:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
        ('organizations', '0004_organization_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('runs_started', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'period_start', 'period_end'), name='unique_automation_usage_period')],
            },
        ),
    ]
