# Generated by Django 6.0.8 on 2026-09-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_automationusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='trigger_type',
            field=models.CharField(choices=[('INCOMING', 'Incoming message'), ('EXACT', 'Exact keyword'), ('CONTAINS', 'Contains keyword'), ('FIRST_INTERACTION', 'First interaction'), ('NEW_LEAD', 'New lead from a message'), ('NEW_CONVERSATION', 'New conversation')], max_length=24),
        ),
    ]
