# Generated by Django 6.0.8 on 2026-08-07 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Designates whether this record has been soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('source_channel', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp')], db_index=True, max_length=20, verbose_name='source channel')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('BOOKING_LINK_SENT', 'Booking Link Sent'), ('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], db_index=True, default='NEW', max_length=25, verbose_name='status')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=15, verbose_name='priority')),
                ('summary', models.CharField(blank=True, help_text='Brief summary of customer inquiry', max_length=255, verbose_name='opportunity summary')),
                ('notes', models.TextField(blank=True, help_text='Internal sales notes, customer preferences, budget remarks', verbose_name='notes')),
                ('qualified_at', models.DateTimeField(blank=True, help_text='Timestamp when lead was marked QUALIFIED', null=True, verbose_name='qualified at')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp when lead reached a terminal status', null=True, verbose_name='closed at')),
                ('assigned_staff', models.ForeignKey(blank=True, help_text='Admin/Staff member assigned to manage this opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, help_text='The communication thread where this lead originated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='conversations.conversation')),
                ('customer', models.ForeignKey(help_text='The customer associated with this sales opportunity', on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='customers.customer')),
                ('originating_message', models.ForeignKey(blank=True, help_text='The first message that triggered this lead opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_leads', to='conversations.message')),
                ('service', models.ForeignKey(blank=True, help_text='Photography service of interest (if identified)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='services.photographyservice')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('activity_type', models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('STATUS_CHANGED', 'Status Changed'), ('STAFF_ASSIGNED', 'Staff Assigned'), ('NOTE_ADDED', 'Note Added'), ('MESSAGE_ATTACHED', 'Message Attached'), ('BOOKING_LINK_SENT', 'Booking Link Sent'), ('BOOKING_CONFIRMED', 'Booking Confirmed')], db_index=True, max_length=30, verbose_name='activity type')),
                ('description', models.TextField(blank=True, help_text='Human-readable log description', verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contextual data (e.g. old_status, new_status, matched_trigger)', verbose_name='metadata')),
                ('actor', models.ForeignKey(blank=True, help_text='Admin user who performed the action (null if automated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(help_text='The lead opportunity this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
                ('message', models.ForeignKey(blank=True, help_text='Attached communication message if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to='conversations.message')),
            ],
            options={
                'verbose_name': 'lead activity',
                'verbose_name_plural': 'lead activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('phrase', models.CharField(db_index=True, help_text='The search phrase or pattern to detect in customer messages', max_length=255, verbose_name='keyword / phrase')),
                ('match_type', models.CharField(choices=[('EXACT', 'Exact Match'), ('CONTAINS', 'Contains Keyword/Phrase'), ('REGEX', 'Regular Expression')], db_index=True, default='CONTAINS', max_length=20, verbose_name='match type')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=15, verbose_name='priority')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this trigger is active during message processing', verbose_name='is active')),
                ('service', models.ForeignKey(blank=True, help_text='Optional service to map when this trigger matches', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers', to='services.photographyservice')),
            ],
            options={
                'verbose_name': 'lead trigger',
                'verbose_name_plural': 'lead triggers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'created_at'], name='leads_lead_status_2b0e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['customer', 'status'], name='leads_lead_custome_2aa92f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source_channel', 'status'], name='leads_lead_source__395913_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['priority', 'status'], name='leads_lead_priorit_904e79_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', '-created_at'], name='leads_leada_lead_id_26db76_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['activity_type', '-created_at'], name='leads_leada_activit_218b18_idx'),
        ),
    ]
