# Generated by Django 5.2.15 on 2026-08-08 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        ('customers', '0001_initial'),
        ('leads', '0001_initial'),
        ('services', '0002_package_alter_photographyservice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status__in', ['NEW', 'CONTACTED', 'QUALIFIED', 'BOOKING_LINK_SENT'])), fields=('customer',), name='unique_active_lead_per_customer'),
        ),
    ]
