# Generated by Django 5.2.15 on 2026-08-08 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_unique_active_lead_per_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='trigger',
            field=models.ForeignKey(blank=True, help_text='The trigger that automatically generated this lead, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_leads', to='leads.leadtrigger'),
        ),
    ]
