# Generated by Django 6.0.8 on 2026-08-09 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversation_conversatio_status_337a05_idx_and_more'),
        ('customers', '0001_initial'),
        ('leads', '0003_lead_trigger'),
        ('services', '0002_package_alter_photographyservice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_staff', 'status'], name='leads_lead_assigne_4655d4_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_deleted'], name='leads_lead_is_dele_45657d_idx'),
        ),
    ]
