# Generated by Django 5.2.15 on 2026-08-16 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_leads_lead_assigne_4655d4_idx_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(help_text='The organization this lead belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='leadtrigger',
            name='organization',
            field=models.ForeignKey(help_text='The organization this trigger belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_triggers', to='organizations.organization'),
        ),
    ]
