# Generated by Django 6.0.8 on 2026-08-16 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_organization'),
        ('customers', '0002_customer_organization'),
        ('leads', '0005_lead_organization_leadtrigger_organization'),
        ('organizations', '0003_organizationinvitation'),
        ('services', '0003_photographyservice_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lead',
            name='unique_active_lead_per_customer',
        ),
        migrations.AddField(
            model_name='lead',
            name='source_identifier',
            field=models.CharField(blank=True, help_text='Optional tracking code, form ID, or external reference', max_length=255, verbose_name='source identifier'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags/labels applied to this lead', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_channel',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp'), ('WEBSITE', 'Website'), ('MANUAL', 'Manual')], db_index=True, max_length=20, verbose_name='source channel'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=25, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('STATUS_CHANGED', 'Status Changed'), ('STAFF_ASSIGNED', 'Staff Assigned'), ('NOTE_ADDED', 'Note Added'), ('MESSAGE_ATTACHED', 'Message Attached')], db_index=True, max_length=30, verbose_name='activity type'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status__in', ['NEW', 'CONTACTED', 'QUALIFIED'])), fields=('customer',), name='unique_active_lead_per_customer'),
        ),
    ]
