# Generated by Django 6.0.8 on 2026-08-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_remove_lead_unique_active_lead_per_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='conversation',
        ),
    ]
