# Generated by Django 6.0.8 on 2026-08-16 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_remove_lead_conversation'),
        ('organizations', '0003_organizationinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Designates whether this record has been soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('name', models.CharField(help_text="Internal name for this form (e.g., 'Main Website Contact')", max_length=255, verbose_name='form name')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='The public identifier used for form submission endpoints', unique=True, verbose_name='public id')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='If disabled, public submissions to this form will be rejected', verbose_name='is active')),
                ('success_message', models.CharField(default='Thank you for your message. We will be in touch shortly.', help_text='Message to display to the user after successful submission', max_length=255, verbose_name='success message')),
                ('fields_config', models.JSONField(blank=True, default=dict, help_text='Optional configuration for required fields or custom branding', verbose_name='fields configuration')),
                ('organization', models.ForeignKey(help_text='The organization this form belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_forms', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'lead form',
                'verbose_name_plural': 'lead forms',
                'ordering': ['-created_at'],
            },
        ),
    ]
