# Generated by Django 5.2.15 on 2026-08-16 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_organizationinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('code', models.CharField(help_text='Internal identifier, e.g., FREE, STARTER, PRO, BUSINESS', max_length=50, unique=True, verbose_name='plan code')),
                ('name', models.CharField(help_text='Display name of the plan', max_length=100, verbose_name='plan name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='monthly price')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='yearly price')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('max_users', models.IntegerField(blank=True, help_text='Maximum number of team members allowed', null=True, verbose_name='max users')),
                ('max_leads', models.IntegerField(blank=True, help_text='Maximum number of leads per month/billing cycle', null=True, verbose_name='max leads')),
                ('max_channels', models.IntegerField(blank=True, help_text='Maximum number of connected channels (WhatsApp, IG)', null=True, verbose_name='max channels')),
                ('max_forms', models.IntegerField(blank=True, help_text='Maximum number of lead capture forms', null=True, verbose_name='max forms')),
                ('max_conversations', models.IntegerField(blank=True, help_text='Maximum number of conversations allowed', null=True, verbose_name='max conversations')),
                ('can_use_instagram', models.BooleanField(default=False, verbose_name='can use instagram')),
                ('can_use_whatsapp', models.BooleanField(default=False, verbose_name='can use whatsapp')),
                ('can_use_website_forms', models.BooleanField(default=True, verbose_name='can use website forms')),
                ('can_add_team_member', models.BooleanField(default=False, verbose_name='can add team member')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20, verbose_name='status')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='trial ends at')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='current period start')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='current period end')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='cancel at period end')),
                ('billing_provider', models.CharField(blank=True, help_text="e.g. 'stripe', 'razorpay'", max_length=50, verbose_name='billing provider')),
                ('provider_customer_id', models.CharField(blank=True, max_length=255, verbose_name='provider customer id')),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255, verbose_name='provider subscription id')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
