# Generated by Django 5.2.15 on 2026-08-22 06:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_contact_email_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('provider', models.CharField(default='razorpay', max_length=50, verbose_name='provider')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='event id')),
                ('event_type', models.CharField(max_length=100, verbose_name='event type')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('is_processed', models.BooleanField(default=False, verbose_name='is processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
            ],
            options={
                'verbose_name': 'payment webhook event',
                'verbose_name_plural': 'payment webhook events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['display_order', 'price_usd'], 'verbose_name': 'plan', 'verbose_name_plural': 'plans'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='can_add_team_member',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_channels',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_conversations',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_forms',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_leads',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price_monthly',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price_yearly',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='trial_ends_at',
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_interval',
            field=models.CharField(default='monthly', max_length=20, verbose_name='billing interval'),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_access_analytics',
            field=models.BooleanField(default=True, verbose_name='can access analytics'),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_use_automations',
            field=models.BooleanField(default=False, verbose_name='can use automations'),
        ),
        migrations.AddField(
            model_name='plan',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='display order'),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of bullet point features for UI display', verbose_name='features list'),
        ),
        migrations.AddField(
            model_name='plan',
            name='lead_limit',
            field=models.IntegerField(default=100, help_text='Combined lead limit per billing period across all channels', verbose_name='lead limit'),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_inr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='monthly price INR'),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='monthly price USD'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_country',
            field=models.CharField(default='IN', help_text='ISO 2-letter country code, e.g. IN, US', max_length=2, verbose_name='billing country'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_currency',
            field=models.CharField(default='INR', help_text='Currency code, e.g. INR, USD', max_length=3, verbose_name='billing currency'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='charged_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='charged amount'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='can_use_instagram',
            field=models.BooleanField(default=True, verbose_name='can use instagram'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='can_use_whatsapp',
            field=models.BooleanField(default=True, verbose_name='can use whatsapp'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('starter', 'Starter'), ('creator', 'Creator'), ('enterprise', 'Enterprise')], help_text='Internal unique identifier: starter, creator, enterprise', max_length=50, unique=True, verbose_name='plan code'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_users',
            field=models.IntegerField(blank=True, help_text='Maximum number of team members allowed (null = unlimited)', null=True, verbose_name='max users'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_provider',
            field=models.CharField(default='razorpay', help_text="e.g. 'razorpay', 'stripe'", max_length=50, verbose_name='billing provider'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='current period start'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='BillingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('provider', models.CharField(default='razorpay', max_length=50, verbose_name='provider')),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, verbose_name='provider payment id')),
                ('provider_order_id', models.CharField(blank=True, max_length=255, verbose_name='provider order id')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='INR', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='status')),
                ('payment_metadata', models.JSONField(blank=True, default=dict, verbose_name='payment metadata')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_transactions', to='organizations.organization')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'billing transaction',
                'verbose_name_plural': 'billing transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('period_start', models.DateTimeField(db_index=True, verbose_name='period start')),
                ('period_end', models.DateTimeField(db_index=True, verbose_name='period end')),
                ('total_leads_count', models.IntegerField(default=0, verbose_name='total leads count')),
                ('instagram_lead_count', models.IntegerField(default=0, verbose_name='instagram lead count')),
                ('whatsapp_lead_count', models.IntegerField(default=0, verbose_name='whatsapp lead count')),
                ('website_lead_count', models.IntegerField(default=0, verbose_name='website lead count')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='organizations.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'usage record',
                'verbose_name_plural': 'usage records',
                'ordering': ['-period_start'],
                'unique_together': {('organization', 'period_start', 'period_end')},
            },
        ),
    ]
