# Generated by Django 6.0.8 on 2026-09-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_paymentwebhookevent_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('creator', 'Creator'), ('enterprise', 'Enterprise')], help_text='Internal unique identifier: free, starter, creator, enterprise', max_length=50, unique=True, verbose_name='plan code'),
        ),
    ]
