# Generated by Django 6.0.8 on 2026-09-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_plan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='automation_run_limit',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='App runs per entitlement month; null means no app quota, not unlimited Meta sending.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='automation_addon_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='automation_addon_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
