# Generated by Django 6.0.8 on 2026-09-05 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_contact_email_and_more'),
        ('subscriptions', '0005_include_creator_enterprise_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='last_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='automation_billing_account',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_account',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='RecurringAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('product', models.CharField(choices=[('plan', 'Plan'), ('dm_automation', 'DM Automation')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=2)),
                ('account_scope', models.CharField(db_index=True, max_length=64)),
                ('provider_plan_id', models.CharField(blank=True, max_length=80)),
                ('provider_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('status', models.CharField(default='creating', max_length=30)),
                ('short_url', models.URLField(blank=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('current_start', models.DateTimeField(blank=True, null=True)),
                ('current_end', models.DateTimeField(blank=True, null=True)),
                ('paid_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=120)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_agreements', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('invoice_id', models.CharField(max_length=80, unique=True)),
                ('payment_id', models.CharField(max_length=80, unique=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='subscriptions.recurringagreement')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.billingtransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='recurringagreement',
            index=models.Index(fields=['organization', 'product', 'account_scope'], name='subscriptio_organiz_afa262_idx'),
        ),
    ]
