import { useState } from "react";
import { Link } from "react-router-dom";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Plus, Zap, ArrowDown, Trash2, Play, History, Pencil } from "lucide-react";
import { apiClient } from "@/api/client";
import { useCurrentSubscription } from "@/api/subscriptions.queries";
import MetaAutomationRules from "./MetaAutomationRules";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { PageContainer } from "@/components/common/layout/PageContainer";
import { PageHeader } from "@/components/common/layout/PageHeader";
import { toast } from "sonner";

type Action = { action_type: string; action_order: number; configuration: Record<string, string> };
type Rule = { id?: string; name: string; channel: string; trigger_type: string; trigger_value: string; priority: number; enabled: boolean; conditions: Record<string, string | boolean>; actions: Action[] };
const fresh = (): Rule => ({ name: "", channel: "INSTAGRAM", trigger_type: "CONTAINS", trigger_value: "", priority: 100, enabled: false, conditions: {}, actions: [{ action_type: "SEND_REPLY", action_order: 0, configuration: { text: "" } }] });
const actionNames: Record<string, string> = { SEND_REPLY: "Send reply", CREATE_LEAD: "Create lead", CHANGE_STATUS: "Change lead status", ADD_TAG: "Add tag", ASSIGN: "Assign lead", BOOKING_LINK: "Send booking link" };
const statuses = ["NEW", "CONTACTED", "QUALIFIED", "CONVERTED", "LOST"];
const selectStyle = "h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm";
function errorText(error: unknown): string {
  const e = error as { response?: { data?: unknown } };
  const data = e.response?.data;
  if (!data || typeof data !== "object") return "Request failed. Please try again.";
  const body = data as Record<string, unknown>;
  const messages = (value: unknown): string[] => {
    if (typeof value === "string") return [value];
    if (Array.isArray(value)) return value.flatMap(messages);
    if (value && typeof value === "object") return Object.values(value).flatMap(messages);
    return [];
  };
  return [...new Set(messages(body.errors || body.detail || body.message))].join(" ") || "Request failed. Please try again.";
}

export default function AutomationsPage() {
  const cache = useQueryClient();
  const subscription = useCurrentSubscription();
  const canEnable = !subscription.isError && !!subscription.data?.automation.entitled;
  const accessReason = subscription.isPending ? "Checking your plan’s automation access…"
    : subscription.isError ? "Could not check automation access. You can still save a draft and retry the plan check."
    : !subscription.data?.is_valid ? "Your subscription is not active. You can save and preview drafts, but activation requires an active plan with DM Automation."
    : subscription.data?.automation.addon_available ? "Starter supports DM Automation with the ₹399/month add-on: 1,000 runs per month. Activate or renew it in Subscription. Drafts and previews remain available."
    : `Your ${subscription.data?.plan.name || "current"} plan does not include DM Automation. You can save and preview drafts. Choose a plan with DM Automation to activate them.`;
  const [draft, setDraft] = useState<Rule | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);
  const openDraft = (rule: Rule) => { setSaveError(null); setDraft(rule); };
  const [history, setHistory] = useState(false);
  const [page, setPage] = useState(1);
  const [previewRule, setPreviewRule] = useState<Rule | null>(null);
  const [sample, setSample] = useState("price");
  const [first, setFirst] = useState(false);
  const [leadId, setLeadId] = useState("");
  const [preview, setPreview] = useState<{ matched: boolean; note: string; actions: Action[] } | null>(null);
  const data = useQuery({ queryKey: ["automations", history, page], queryFn: async () => (await apiClient.get(history ? "/automations/history/" : "/automations/", { params: { page } })).data, refetchInterval: history ? 10000 : false });
  const members = useQuery({ queryKey: ["automation-members"], queryFn: async () => (await apiClient.get("/organizations/team/")).data, enabled: !!draft });
  const save = useMutation({ mutationFn: async (rule: Rule) => rule.id ? apiClient.put(`/automations/${rule.id}/`, rule) : apiClient.post("/automations/", rule), onSuccess: (_, rule) => { setDraft(null); cache.invalidateQueries({ queryKey: ["automations"] }); toast.success(rule.enabled ? "Automation saved" : "Automation saved as a draft. It will not run until enabled."); }, onError: e => { setSaveError(errorText(e)); const response = e as { response?: { data?: { errors?: { enabled?: unknown } } } }; if (response.response?.data?.errors?.enabled) cache.invalidateQueries({ queryKey: ["subscriptions", "current"] }); } });
  const toggle = useMutation({ mutationFn: (rule: Rule) => apiClient.patch(`/automations/${rule.id}/`, { enabled: !rule.enabled }), onSuccess: () => cache.invalidateQueries({ queryKey: ["automations"] }), onError: e => toast.error(errorText(e)) });
  const remove = useMutation({ mutationFn: (id: string) => apiClient.delete(`/automations/${id}/`), onSuccess: () => cache.invalidateQueries({ queryKey: ["automations"] }), onError: e => toast.error(errorText(e)) });
  const test = useMutation({ mutationFn: async () => (await apiClient.post(`/automations/${previewRule?.id}/test/`, { text: sample, first_interaction: first, new_lead: previewRule?.trigger_type === "NEW_LEAD" && first, ...(leadId ? { lead_id: leadId } : {}) })).data, onSuccess: setPreview, onError: e => toast.error(errorText(e)) });
  const updateAction = (index: number, patch: Partial<Action>) => setDraft(d => d && ({ ...d, actions: d.actions.map((a, i) => i === index ? { ...a, ...patch } : a) }));
  const rows = data.data?.results || [];
  return <PageContainer>
    <PageHeader title="DM Automation" description="Turn incoming conversations into timely replies and organized leads." />
    {canEnable && <div role="status" className="mt-5 rounded-lg border bg-white p-4 text-sm"><strong>{subscription.data?.automation.runs_used.toLocaleString()} / {subscription.data?.automation.run_limit?.toLocaleString() ?? "No app cap"} automation runs used</strong><p className="mt-1 text-slate-600">{subscription.data?.automation.period_end && `Period ends ${new Date(subscription.data.automation.period_end).toLocaleDateString()}. `}Meta messaging limits and fees apply separately.</p>{subscription.data?.automation.runs_remaining === 0 && <p className="mt-2 text-amber-800">Monthly allowance reached. New runs are blocked until the next paid period; drafts and previews remain available.</p>}</div>}
    <MetaAutomationRules />
    <div className="mt-6 flex flex-wrap items-center justify-between gap-3">
      <div className="flex gap-2"><Button variant={!history ? "default" : "outline"} onClick={() => { setHistory(false); setPage(1); }}><Zap className="mr-2 h-4 w-4" />Rules</Button><Button variant={history ? "default" : "outline"} onClick={() => { setHistory(true); setPage(1); }}><History className="mr-2 h-4 w-4" />Execution history</Button></div>
      <Button onClick={() => openDraft(fresh())}><Plus className="mr-2 h-4 w-4" />Create automation</Button>
    </div>
    <p className="my-5 text-sm text-slate-500">Rules run in priority order on new customer messages. Replies respect Meta’s messaging window. Queued replies are tracked separately from completed lead actions.</p>
    {!canEnable && <div className="mb-5 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><p role="status">{accessReason}</p><div className="mt-3 flex gap-2">{!subscription.isPending && <Button variant="outline" size="sm" asChild><Link to="/app/settings/subscription">View plans</Link></Button>}{subscription.isError && <Button variant="outline" size="sm" disabled={subscription.isFetching} onClick={() => subscription.refetch()}>Retry plan check</Button>}</div></div>}
    {data.isLoading ? <p role="status">Loading automations…</p> : data.isError ? <div role="alert" className="p-6 border rounded-xl"><p>{errorText(data.error)}</p><Button variant="outline" onClick={() => data.refetch()}>Retry</Button></div> : !rows.length ? <div className="border border-dashed rounded-xl py-16 text-center"><Zap className="mx-auto mb-4 h-8 w-8 text-slate-400" /><h2 className="text-lg font-semibold">{history ? "No executions yet" : "Your first reply starts here"}</h2><p className="mt-2 text-sm text-slate-500">{history ? "Matching incoming messages will appear here with action results." : "Create a keyword rule, add actions, and preview it before enabling."}</p></div> : <div className="divide-y rounded-xl border bg-white">
      {rows.map((row: any) => history ? <article key={row.id} className="p-5"><div className="flex justify-between gap-4"><strong>{row.automation_name}</strong><span className="text-xs rounded-full bg-slate-100 px-3 py-1">{row.status}</span></div><p className="mt-1 text-xs text-slate-500">{new Date(row.created_at).toLocaleString()}</p><div className="mt-3 flex flex-wrap gap-3 text-sm">{row.result.map((r: any, i: number) => <span key={i}>{actionNames[r.action]} · {r.status}</span>)}</div>{row.delivery.map((m: any) => <p key={m.id} className="mt-2 text-sm">Reply: {m.delivery_status}{m.error_message && ` — ${m.error_message}`}</p>)}{row.error && <p role="alert" className="mt-2 text-sm text-red-700">{row.error}</p>}</article> : <article key={row.id} className="p-5 flex flex-wrap justify-between items-center gap-4"><div><h2 className="font-semibold">{row.name}</h2><p className="text-sm text-slate-500 mt-1">{row.channel} · {row.trigger_type.replaceAll("_", " ")}{row.trigger_value && ` “${row.trigger_value}”`} · Priority {row.priority}</p><p className="text-xs text-slate-500 mt-2">{row.actions.map((a: Action) => actionNames[a.action_type]).join(" → ")}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant={row.enabled ? "default" : "outline"} disabled={toggle.isPending || (!row.enabled && !canEnable)} title={!row.enabled && !canEnable ? accessReason : undefined} onClick={() => toggle.mutate(row)}>{row.enabled ? "Enabled" : "Disabled"}</Button><Button size="sm" variant="outline" onClick={() => { setPreviewRule(row); setPreview(null); }}><Play className="mr-1 h-3 w-3" />Preview</Button><Button size="icon" variant="ghost" aria-label={`Edit ${row.name}`} onClick={() => openDraft(structuredClone(row))}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" aria-label={`Delete ${row.name}`} disabled={remove.isPending} onClick={() => { if (window.confirm(`Delete “${row.name}”? Execution history will be retained.`)) remove.mutate(row.id); }}><Trash2 className="h-4 w-4" /></Button></div></article>)}
    </div>}
    <div className="mt-4 flex justify-end gap-2"><Button variant="outline" disabled={page === 1} onClick={() => setPage(p => p-1)}>Previous</Button><span className="p-2 text-sm">Page {page}</span><Button variant="outline" disabled={!data.data?.next} onClick={() => setPage(p => p+1)}>Next</Button></div>
    <Dialog open={!!draft} onOpenChange={open => { if (!open) setDraft(null); }}><DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{draft?.id ? "Edit automation" : "Create automation"}</DialogTitle></DialogHeader>{draft && <form className="space-y-5" onSubmit={e => { e.preventDefault(); setSaveError(null); if (draft.enabled && !canEnable) { setSaveError(accessReason + " Uncheck Enable after saving to save a draft."); return; } save.mutate(draft); }}>
      <label className="block text-sm font-medium">Name<Input required maxLength={160} className="mt-2" value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} placeholder="Pricing inquiry" /></label>
      <div className="grid grid-cols-2 gap-4"><label className="text-sm font-medium">Channel<select className={`${selectStyle} mt-2`} value={draft.channel} onChange={e => setDraft({ ...draft, channel: e.target.value })}><option>INSTAGRAM</option><option>WHATSAPP</option></select></label><label className="text-sm font-medium">Priority<Input type="number" min={0} max={32767} className="mt-2" value={draft.priority} onChange={e => setDraft({ ...draft, priority: Number(e.target.value) })} /></label></div>
      <fieldset className="border-t pt-4 space-y-3"><legend className="font-semibold text-sm px-1">When a customer sends a message</legend><select aria-label="Trigger type" className={selectStyle} value={draft.trigger_type} onChange={e => setDraft({ ...draft, trigger_type: e.target.value })}><option value="CONTAINS">Contains keyword</option><option value="EXACT">Exact keyword</option><option value="INCOMING">Any incoming message</option><option value="FIRST_INTERACTION">First interaction</option><option value="NEW_CONVERSATION">New conversation</option><option value="NEW_LEAD">New lead from a message</option></select>{["EXACT", "CONTAINS"].includes(draft.trigger_type) && <Input aria-label="Trigger keyword" required maxLength={255} placeholder="e.g. price" value={draft.trigger_value} onChange={e => setDraft({ ...draft, trigger_value: e.target.value })} />}</fieldset>
      <fieldset className="border-t pt-4 space-y-3"><legend className="font-semibold text-sm px-1">Optional conditions</legend><select aria-label="Required lead status" className={selectStyle} value={String(draft.conditions.lead_status || "")} onChange={e => { const conditions = { ...draft.conditions }; if (e.target.value) conditions.lead_status = e.target.value; else delete conditions.lead_status; setDraft({ ...draft, conditions }); }}><option value="">Any lead status</option>{statuses.map(s => <option key={s}>{s}</option>)}</select><Input aria-label="Required tag" maxLength={80} placeholder="Required tag (optional)" value={String(draft.conditions.has_tag || "")} onChange={e => { const conditions = { ...draft.conditions }; if (e.target.value) conditions.has_tag = e.target.value; else delete conditions.has_tag; setDraft({ ...draft, conditions }); }} /></fieldset>
      <fieldset className="border-t pt-4 space-y-3"><legend className="font-semibold text-sm px-1">Then perform these actions</legend>{draft.actions.map((a, i) => <div key={i} className="border-l-2 border-rose-200 pl-4 py-2 space-y-3"><div className="flex gap-2 items-center"><span className="text-xs text-slate-400">{i+1}</span><select aria-label={`Action ${i+1}`} className={selectStyle} value={a.action_type} onChange={e => updateAction(i, { action_type: e.target.value, configuration: {} })}>{Object.entries(actionNames).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select><Button type="button" size="icon" variant="ghost" aria-label="Move action down" disabled={i === draft.actions.length-1} onClick={() => { const actions = [...draft.actions]; [actions[i], actions[i+1]] = [actions[i+1], actions[i]]; setDraft({ ...draft, actions: actions.map((a, j) => ({ ...a, action_order: j })) }); }}><ArrowDown className="h-4 w-4" /></Button><Button type="button" size="icon" variant="ghost" aria-label="Remove action" disabled={draft.actions.length === 1} onClick={() => setDraft({ ...draft, actions: draft.actions.filter((_, j) => j !== i).map((a, j) => ({ ...a, action_order: j })) })}><Trash2 className="h-4 w-4" /></Button></div>
        {["SEND_REPLY", "BOOKING_LINK"].includes(a.action_type) && <Textarea aria-label="Reply text" required={a.action_type === "SEND_REPLY"} maxLength={a.action_type === "SEND_REPLY" ? 1000 : 700} rows={3} value={a.configuration.text || ""} onChange={e => updateAction(i, { configuration: { text: e.target.value } })} placeholder={a.action_type === "BOOKING_LINK" ? "Introduction (a private booking URL is appended)" : "Thanks for reaching out! Here are our pricing details…"} />}
        {a.action_type === "ADD_TAG" && <Input aria-label="Tag to add" required maxLength={80} value={a.configuration.tag || ""} onChange={e => updateAction(i, { configuration: { tag: e.target.value } })} placeholder="Demo Interested" />}
        {a.action_type === "CHANGE_STATUS" && <select aria-label="New lead status" required className={selectStyle} value={a.configuration.status || ""} onChange={e => updateAction(i, { configuration: { status: e.target.value } })}><option value="">Choose status</option>{statuses.map(s => <option key={s}>{s}</option>)}</select>}
        {a.action_type === "ASSIGN" && <select aria-label="Assign to member" required className={selectStyle} value={a.configuration.user_id || ""} onChange={e => updateAction(i, { configuration: { user_id: e.target.value } })}><option value="">Choose team member</option>{(members.data?.results || members.data || []).map((m: any) => <option key={m.id} value={m.user?.id || m.user_id || m.id}>{m.user?.full_name || m.full_name || m.email}</option>)}</select>}
      </div>)}<Button type="button" variant="outline" disabled={draft.actions.length >= 10} onClick={() => setDraft({ ...draft, actions: [...draft.actions, { action_type: "ADD_TAG", action_order: draft.actions.length, configuration: {} }] })}><Plus className="mr-2 h-4 w-4" />Add action</Button></fieldset>
      <div className="space-y-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.enabled} disabled={!canEnable && !draft.enabled} aria-describedby={!canEnable ? "automation-plan-access" : undefined} onChange={e => { setSaveError(null); setDraft({ ...draft, enabled: e.target.checked }); }} />Enable after saving</label>{!canEnable && <p id="automation-plan-access" className="text-sm text-slate-600">{accessReason}{draft.enabled && " Uncheck Enable after saving to save this automation as a disabled draft."}</p>}</div>
      {saveError && <p role="alert" className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{saveError}</p>}
      <div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="outline" onClick={() => setDraft(null)}>Cancel</Button><Button disabled={save.isPending} type="submit">{save.isPending ? "Saving…" : draft.enabled ? "Save automation" : "Save draft"}</Button></div>
    </form>}</DialogContent></Dialog>
    <Dialog open={!!previewRule} onOpenChange={open => { if (!open) setPreviewRule(null); }}><DialogContent><DialogHeader><DialogTitle>Preview “{previewRule?.name}”</DialogTitle></DialogHeader><p className="text-sm text-slate-500">No messages are sent and no leads are changed.</p><Textarea aria-label="Sample incoming message" maxLength={1000} value={sample} onChange={e => setSample(e.target.value)} /><Input aria-label="Lead ID for conditions" placeholder="Optional lead ID for evaluating conditions" value={leadId} onChange={e => setLeadId(e.target.value)} /><label className="text-sm flex gap-2"><input type="checkbox" checked={first} onChange={e => setFirst(e.target.checked)} />{previewRule?.trigger_type === "NEW_LEAD" ? "A new lead is captured by this message" : "First interaction"}</label><Button disabled={test.isPending} onClick={() => test.mutate()}>Test rule</Button>{preview && <div role="status" className="rounded-lg bg-slate-50 p-4"><strong>{preview.matched ? "Rule matches" : "Rule does not match"}</strong><p className="text-sm mt-2">{preview.actions.map(a => actionNames[a.action_type]).join(" → ")}</p><p className="text-xs text-slate-500 mt-2">{preview.note}</p></div>}</DialogContent></Dialog>
  </PageContainer>;
}
