# Generated by Django 6.0.8 on 2026-08-07 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_package_alter_photographyservice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='closure date')),
                ('name', models.CharField(help_text="e.g. Diwali, New Year's Day, Studio Renovation", max_length=255, verbose_name='holiday / closure name')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'holiday / studio closure',
                'verbose_name_plural': 'holidays & studio closures',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SpecialAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('date', models.DateField(db_index=True, verbose_name='override date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('reason', models.CharField(blank=True, help_text='e.g. Festival Special Shoot, Extended Weekend', max_length=255, verbose_name='reason')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'special availability',
                'verbose_name_plural': 'special availabilities',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'is_active', 'start_time'], name='scheduling__date_39cda3_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True, verbose_name='day of week')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'weekly availability',
                'verbose_name_plural': 'weekly availabilities',
                'ordering': ['weekday', 'start_time'],
                'indexes': [models.Index(fields=['weekday', 'is_active', 'start_time'], name='scheduling__weekday_cf353f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockedPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(db_index=True, verbose_name='ends at')),
                ('reason', models.CharField(help_text='e.g. Studio Maintenance, Private Event, Personal Leave', max_length=255, verbose_name='reason')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('service', models.ForeignKey(blank=True, help_text='Optional specific service blocked. If blank, all services are blocked.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_periods', to='services.photographyservice')),
            ],
            options={
                'verbose_name': 'blocked period',
                'verbose_name_plural': 'blocked periods',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='scheduling__is_acti_417f7f_idx')],
            },
        ),
    ]
