# Generated by Django 6.0.8 on 2026-08-07 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LEAD_STATUS_CHANGED', 'Lead Status Changed'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('BOOKING_CREATED', 'Booking Created'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('AVAILABILITY_CHANGED', 'Availability Changed'), ('SERVICE_CHANGED', 'Service Changed'), ('BOOKING_LINK_GENERATED', 'Booking Link Generated'), ('BOOKING_LINK_SENT', 'Booking Link Sent'), ('INTEGRATION_SETTINGS_CHANGED', 'Integration Settings Changed'), ('STAFF_ROLE_CHANGED', 'Staff Role Changed'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('CUSTOM', 'Custom Action')], db_index=True, help_text='Standardized audit action code.', max_length=64, verbose_name='action')),
                ('entity_type', models.CharField(db_index=True, help_text='Class name of the affected domain entity (e.g. Lead, Booking).', max_length=100, verbose_name='entity type')),
                ('entity_id', models.CharField(blank=True, db_index=True, default='', help_text='Identifier of the affected entity (e.g. UUID, PK, or slug).', max_length=255, verbose_name='entity identifier')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Sanitized context, diffs, or details about the event.', verbose_name='metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address where available.', null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Exact UTC timestamp when the audit event was recorded.', verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (null for system/webhook actions).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'db_table': 'audit_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_event_action_263795_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_event_entity__1d80e9_idx'), models.Index(fields=['actor', 'created_at'], name='audit_event_actor_i_e566c4_idx')],
            },
        ),
    ]
