# Generated by Django 6.0.8 on 2026-09-05 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('organizations', '0004_organization_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
