# Generated by Django 6.0.8 on 2026-08-07 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('leads', '0001_initial'),
        ('services', '0002_package_alter_photographyservice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Designates whether this record has been soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('starts_at', models.DateTimeField(db_index=True, help_text='Scheduled session start time (timezone aware)', verbose_name='starts at')),
                ('ends_at', models.DateTimeField(db_index=True, help_text='Scheduled session end time (timezone aware)', verbose_name='ends at')),
                ('buffer_before_minutes', models.PositiveIntegerField(default=0, help_text='Preparation buffer before session start', verbose_name='buffer before (minutes)')),
                ('buffer_after_minutes', models.PositiveIntegerField(default=0, help_text='Cleanup buffer after session end', verbose_name='buffer after (minutes)')),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved (Pending Confirmation)'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='CONFIRMED', max_length=20, verbose_name='booking status')),
                ('notes', models.TextField(blank=True, help_text='Internal studio notes or customer special requests', verbose_name='notes')),
                ('customer', models.ForeignKey(help_text='Customer attending the photoshoot', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer')),
                ('lead', models.ForeignKey(blank=True, help_text='Originating sales lead if converted from inbound inquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='leads.lead')),
                ('package', models.ForeignKey(blank=True, help_text='Optional specific package booked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.package')),
                ('service', models.ForeignKey(help_text='The booked photography service', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.photographyservice')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['status', 'starts_at', 'ends_at'], name='bookings_bo_status_b7eab3_idx'), models.Index(fields=['customer', 'status'], name='bookings_bo_custome_0cbf77_idx')],
            },
        ),
    ]
