# Generated by Django 6.0.8 on 2026-08-07 19:46

import apps.bookings.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('customers', '0001_initial'),
        ('leads', '0001_initial'),
        ('services', '0002_package_alter_photographyservice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='BookingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('token', models.CharField(db_index=True, default=apps.bookings.models.generate_booking_token, help_text='Cryptographically secure URL-safe token', max_length=64, unique=True, verbose_name='secure token')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Expiration timestamp after which the link cannot be used', verbose_name='expires at')),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this booking link was successfully redeemed', verbose_name='is used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('is_revoked', models.BooleanField(db_index=True, default=False, help_text='Manually revoked by studio admin', verbose_name='is revoked')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
            ],
            options={
                'verbose_name': 'booking link',
                'verbose_name_plural': 'booking links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.AddField(
            model_name='booking',
            name='blocked_ends_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Latest studio lock timestamp including cleanup buffer', null=True, verbose_name='blocked ends at'),
        ),
        migrations.AddField(
            model_name='booking',
            name='blocked_starts_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Earliest studio lock timestamp including preparation buffer', null=True, verbose_name='blocked starts at'),
        ),
        migrations.AddField(
            model_name='booking',
            name='blocked_time_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, help_text='PostgreSQL GiST indexed range for physical exclusion constraints', null=True, verbose_name='blocked time range'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the booking was finalized', verbose_name='booked at'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp if the booking was cancelled', null=True, verbose_name='cancelled at'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Notes provided by the customer during booking', verbose_name='customer notes'),
        ),
        migrations.AddField(
            model_name='booking',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Private studio notes or operational instructions', verbose_name='internal notes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='CONFIRMED', max_length=20, verbose_name='booking status'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_deleted', False), ('status__in', ['PENDING', 'CONFIRMED'])), expressions=[('blocked_time_range', '&&')], name='exclude_overlapping_active_bookings'),
        ),
        migrations.AddField(
            model_name='bookinglink',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who generated this link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_booking_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookinglink',
            name='lead',
            field=models.ForeignKey(help_text='The sales lead this link was generated for', on_delete=django.db.models.deletion.CASCADE, related_name='booking_links', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='bookinglink',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Optional pre-selected photography service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_links', to='services.photographyservice'),
        ),
        migrations.AddIndex(
            model_name='bookinglink',
            index=models.Index(fields=['token', 'is_used', 'is_revoked'], name='bookings_bo_token_85b3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinglink',
            index=models.Index(fields=['lead', '-created_at'], name='bookings_bo_lead_id_a70171_idx'),
        ),
    ]
