# Generated by Django 6.0.8 on 2026-08-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookinglink_remove_booking_notes_and_more'),
        ('customers', '0001_initial'),
        ('leads', '0003_lead_trigger'),
        ('services', '0002_package_alter_photographyservice_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['is_deleted'], name='bookings_bo_is_dele_c46860_idx'),
        ),
    ]
