# Generated by Django 6.0.8 on 2026-09-05 06:44

import django.contrib.postgres.constraints
import django.db.models.deletion
from django.db import migrations, models


def backfill_organizations(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    for booking in Booking.objects.select_related("customer").filter(organization__isnull=True).iterator():
        if booking.customer.organization_id:
            Booking.objects.filter(pk=booking.pk).update(organization_id=booking.customer.organization_id)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_bookings_bo_is_dele_c46860_idx'),
        ('customers', '0004_backfill_identity_organization'),
        ('leads', '0008_leadform'),
        ('organizations', '0004_organization_contact_email_and_more'),
        ('services', '0003_photographyservice_organization_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='exclude_overlapping_active_bookings',
        ),
        migrations.AddField(
            model_name='booking',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.RunPython(backfill_organizations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_deleted', False), ('status__in', ['PENDING', 'CONFIRMED'])), expressions=[('blocked_time_range', '&&'), ('organization', '=')], name='exclude_tenant_overlapping_bookings'),
        ),
    ]
