# Generated by Django 5.2.15 on 2026-08-16 09:19

from django.db import migrations

def create_default_organization_and_migrate_data(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    OrganizationMembership = apps.get_model('organizations', 'OrganizationMembership')
    User = apps.get_model('accounts', 'User')
    Customer = apps.get_model('customers', 'Customer')
    Lead = apps.get_model('leads', 'Lead')
    LeadTrigger = apps.get_model('leads', 'LeadTrigger')
    Conversation = apps.get_model('conversations', 'Conversation')
    PhotographyService = apps.get_model('services', 'PhotographyService')

    if not User.objects.exists() and not Customer.objects.exists():
        # Nothing to migrate
        return

    # Create default organization
    owner = User.objects.order_by('created_at').first()
    default_org = Organization.objects.create(
        name="V4 Studio",
        slug="v4-studio",
        owner=owner,
        is_active=True
    )

    # Add all users to the organization
    for user in User.objects.all():
        role = "OWNER" if user == owner else "ADMIN"
        OrganizationMembership.objects.create(
            organization=default_org,
            user=user,
            role=role
        )

    # Migrate all existing data to the default organization
    Customer.objects.update(organization=default_org)
    Lead.objects.update(organization=default_org)
    LeadTrigger.objects.update(organization=default_org)
    Conversation.objects.update(organization=default_org)
    PhotographyService.objects.update(organization=default_org)


def reverse_migration(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    Organization.objects.filter(slug="v4-studio").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('accounts', '0002_alter_user_is_staff'),
        ('customers', '0002_customer_organization'),
        ('leads', '0005_lead_organization_leadtrigger_organization'),
        ('conversations', '0004_conversation_organization'),
        ('services', '0003_photographyservice_organization_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_organization_and_migrate_data, reverse_migration),
    ]
