# Generated by Django 5.2.15 on 2026-08-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary public contact email', max_length=254, verbose_name='contact email'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Primary public contact phone number', max_length=50, verbose_name='contact phone'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.URLField(blank=True, help_text="URL to the organization's logo image", max_length=1000, null=True, verbose_name='logo URL'),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Primary timezone for the organization (e.g. America/New_York)', max_length=100, verbose_name='timezone'),
        ),
    ]
