# Generated by Django 6.0.8 on 2026-09-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text='Primary timezone for the organization (e.g. America/New_York)', max_length=100, verbose_name='timezone'),
        ),
    ]
