# Generated by Django 6.0.8 on 2026-08-07 20:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('channel', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp')], help_text='Delivery channel (Instagram or WhatsApp)', max_length=20)),
                ('notification_type', models.CharField(choices=[('BOOKING_LINK', 'Booking Link'), ('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('BOOKING_REMINDER', 'Booking Reminder'), ('BOOKING_CANCELLATION', 'Booking Cancellation'), ('GENERAL', 'General Notification')], default='GENERAL', help_text='Functional domain purpose of the notification', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current delivery status', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Unique key preventing duplicate outbound dispatches', max_length=255, null=True, unique=True)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Dynamic parameters passed for template/copy formatting')),
                ('rendered_text', models.TextField(blank=True, help_text='Final rendered message body sent to recipient')),
                ('external_message_id', models.CharField(blank=True, db_index=True, help_text='Provider message ID (e.g. wamid or IG mid) for webhook correlation', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Diagnostic failure details if delivery failed')),
                ('is_permanent_error', models.BooleanField(default=False, help_text='If True, indicates unrecoverable failure and halts Celery retries')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of attempted delivery retries')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when provider accepted the message', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Timestamp when message reached recipient device', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when recipient opened the message', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='Timestamp when message permanently or transiently failed', null=True)),
                ('customer', models.ForeignKey(help_text='Target recipient customer', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.customer')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'status'], name='notificatio_channel_411e8e_idx'), models.Index(fields=['customer', 'status'], name='notificatio_custome_e8749c_idx'), models.Index(fields=['external_message_id'], name='notificatio_externa_960263_idx')],
            },
        ),
    ]
