# Generated by Django 6.0.8 on 2026-08-07 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Designates whether this record has been soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('channel', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp')], db_index=True, max_length=20, verbose_name='channel')),
                ('external_thread_id', models.CharField(blank=True, db_index=True, help_text='Platform-specific thread or conversation identifier if available', max_length=255, verbose_name='external thread id')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20, verbose_name='status')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the most recent message in this conversation', null=True, verbose_name='last message at')),
                ('last_message_preview', models.CharField(blank=True, help_text='Snippet of the most recent message', max_length=255, verbose_name='last message preview')),
                ('unread_count', models.PositiveIntegerField(db_index=True, default=0, help_text='Number of unread inbound messages for admin review', verbose_name='unread count')),
                ('customer', models.ForeignKey(help_text='The customer participating in this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='customers.customer')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], db_index=True, help_text='Message flow direction', max_length=10, verbose_name='direction')),
                ('external_message_id', models.CharField(blank=True, db_index=True, help_text='Unique identifier from WhatsApp (wamid) or Instagram for deduplication', max_length=255, verbose_name='external message id')),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], db_index=True, default='TEXT', max_length=20, verbose_name='message type')),
                ('text', models.TextField(blank=True, help_text='Normalized text message content', verbose_name='text content')),
                ('attachment_metadata', models.JSONField(blank=True, default=dict, help_text='Structured metadata for media (URL, mime type, size, thumbnail)', verbose_name='attachment metadata')),
                ('provider_timestamp', models.DateTimeField(blank=True, db_index=True, help_text='Message creation timestamp sent by Meta webhook', null=True, verbose_name='provider timestamp')),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], db_index=True, default='DELIVERED', max_length=20, verbose_name='delivery status')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Original sanitized webhook payload for debugging/audit', verbose_name='raw payload')),
                ('conversation', models.ForeignKey(help_text='The parent conversation thread', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['channel', 'status'], name='conversatio_channel_f78ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='conversatio_last_me_6a7e57_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['customer', '-last_message_at'], name='conversatio_custome_955e0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('customer', 'channel'), name='unique_customer_channel_conversation'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_4b968d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['direction', 'created_at'], name='conversatio_directi_b94388_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['external_message_id'], name='conversatio_externa_c7658c_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_message_id', ''), _negated=True), fields=('external_message_id',), name='unique_external_message_id'),
        ),
    ]
