# Generated by Django 5.2.15 on 2026-08-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Tracks whether this specific message has been read by the admin', verbose_name='is read'),
        ),
    ]
