# Generated by Django 6.0.8 on 2026-08-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_message_is_read'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'unread_count'], name='conversatio_status_337a05_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_deleted'], name='conversatio_is_dele_a5d77c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'delivery_status'], name='conversatio_convers_0908a9_idx'),
        ),
    ]
