# Generated by Django 5.2.15 on 2026-08-16 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversation_conversatio_status_337a05_idx_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(help_text='The organization this conversation belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='organizations.organization'),
        ),
    ]
