# Generated by Django 6.0.8 on 2026-08-16 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_organization'),
        ('customers', '0002_customer_organization'),
        ('leads', '0007_remove_lead_conversation'),
        ('organizations', '0003_organizationinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='Staff member assigned to manage this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='The sales lead associated with this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_inbox', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Staff member who sent the message (if OUTBOUND)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='channel',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp'), ('WEBSITE', 'Website')], db_index=True, max_length=20, verbose_name='channel'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['assigned_user', 'status'], name='conversatio_assigne_7b95cd_idx'),
        ),
    ]
