# Generated by Django 6.0.8 on 2026-09-05 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_backfill_conversation_organization'),
        ('organizations', '0004_organization_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('channel', models.CharField(max_length=20)),
                ('external_message_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('provider_timestamp', models.DateTimeField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'channel', 'external_message_id', 'status'), name='unique_tenant_message_receipt')],
            },
        ),
    ]
